[general]
  # The local hostname which is used to greet incoming requests
  hostname   = "localhost"

  # A list of domains this server is accepting mails for
  domains    = [ "localhost" ]

[addressbook]
  filename = "_example/addressbook.toml"

[mail]
  # Limit the maximum accepted mail size to be 25 MB
  # see <https://tools.ietf.org/html/rfc1870>
  size       = 26214400

[hook.spf]
  # Enable the "Sender Policy Framework (SPF)"
  # see <https://tools.ietf.org/html/rfc7208>
  enable     = true

[hook.dnsbl]
  # Enable blacklisting using "DNS Blacklists"
  # see <https://tools.ietf.org/html/rfc5782>
  enable     = true
  servers    = [ "zen.spamhaus.org" ]

[tls]
  # Use standard pem encoded files to load the certificate
  source     = "files"
  crt        = "cert/briefmail.crt"
  key        = "cert/briefmail.key"

  # Extract a certificate from <https://traefik.io/>
  # source     = "traefik"
  # acme       = "/etc/traefik/acme.json"
  # domain     = "localhost"

[[smtp]]
  address    = ":25"

[[smtp]]
  address    = ":587"

[[pop3]]
  address    = ":110"

[[pop3]]
  address    = ":995"
  # Force tls on port 995 from the start
  tls        = true
