name: Build & Test
on: push

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.13, 1.14 ]
    name: Build & Test with Go ${{ matrix.go }}

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Tools
        run: |
          go get github.com/google/wire/cmd/wire

      - name: Build
        run: make build

      - name: Test
        run: go test ./...
