name: Build
on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Tools
      run: |
        go get golang.org/x/lint/golint
        go get github.com/google/wire/cmd/wire

    - name: Build
      run: make build

    - name: Test
      run: go test ./...
