name: CI
on: push

jobs:

  ci:
    name: CI with Go ${{ matrix.go }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ 1.13, 1.14, 1.15 ]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install build tools
        run: |
          go get github.com/google/wire/cmd/wire

      - name: Build
        run: make build

      - name: Test
        run: go test ./...

      - name: Install lint tools
        run: |
          go get golang.org/x/lint/golint

      - name: go vet
        run: go vet ./...

      - name: golint
        run: golint -set_exit_status ./...
