name: CI
on: push

jobs:

  ci:
    name: CI with Go ${{ matrix.go }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ 1.16 ]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install build tools
        run: |
          go get -v github.com/google/wire/cmd/wire

      - name: Build
        run: make build

      - name: Install test tools
        run: |
          go get -v github.com/vektra/mockery/v2

      - name: Test
        run: |
          make test

      - name: Upload testcoverage
        uses: codecov/codecov-action@v1
        with:
          name: Go ${{ matrix.go }}
          file: ./target/coverage.txt
          fail_ci_if_error: true

      - name: Install lint tools
        run: |
          go get -v golang.org/x/lint/golint

      - name: go vet
        run: |
          go vet ./...

      - name: golint
        run: |
          golint -set_exit_status ./...
